server:
  port: 8888
spring:
  application:
    name: ninesong-auth
  cloud:
    nacos:
      discovery:
        server-addr: 101.34.148.140:8848
  datasource:
    url:
    username: root
    password: admin2588
    driver-class-name: com.mysql.cj.jdbc.Driver