server:
  port: 9998
spring:
  application:
    name: ninesong-user
  cloud:
    nacos:
      discovery:
        server-addr: 101.34.148.140:8848
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver