server:
  port: 9997
spring:
  application:
    name: ninesong-user
  cloud:
    nacos:
      discovery:
        server-addr: 101.34.148.140:8848
  #数据源
  datasource:
    url: jdbc:mysql://101.34.148.140:3306/nine_song
    username: root
    password: admin2588
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:org/jeecg/modules/**/xml/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型
      id-type: auto
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true